### ISSUE TITLE
doesn't start

### ISSUE THREAD

**Issue by jlslegalize** [JeffHoogland/ePad#13]
`
jls@box:~$ epad
Traceback (most recent call last):
  File "/usr/bin/epad", line 88, in <module>
    from efl.evas import EVAS_HINT_EXPAND, EVAS_HINT_FILL, \
ImportError: /usr/lib/python2.7/dist-packages/efl/evas.i386-linux-gnu.so: undefined symbol: _eo_do_end
jls@box:~$

`

**Comment by JeffHoogland** [comment]
What version of Py-EFL are you using?

**Comment by jlslegalize** [comment]
hi jeff
git

**Comment by JeffHoogland** [comment]
Please try it with python-efl 1.15 - it works fine here with that version. If it doesn't work with newer releases please open a ticket with the upstream project because that means they broke backwards compatibility.

**Comment by kaihu** [comment]
Because Eo API changes between versions of EFL you need to have the versions matching, I.E. with efl-1.16.x you should have python-efl-1.16.x
When using git you may need a few days older revision of EFL as the maintainers of the projects are different people and Python-EFL may not have kept up with the latest changes.
